@echo off
REM ML Kraken Pro Live Trader - Interactive Setup Wizard
REM This script walks you through complete system configuration

setlocal enabledelayedexpansion

echo ================================================================================
echo ML KRAKEN PRO LIVE TRADER - SETUP WIZARD
echo ================================================================================
echo.
echo This wizard will help you configure the trading system.
echo You'll need: 5 Kraken API keys and your portfolio information
echo.
pause

REM Check Python
echo [1/10] Checking Python installation...
python --version >nul 2>&1
if errorlevel 1 (
    echo ERROR: Python not found!
    echo Please install Python 3.10+ from https://www.python.org/
    pause
    exit /b 1
)
python --version
echo.

REM Install dependencies
echo [2/10] Installing dependencies...
echo This may take 2-3 minutes...
pip install -r requirements.txt --quiet
if errorlevel 1 (
    echo ERROR: Failed to install dependencies
    pause
    exit /b 1
)
echo Dependencies installed successfully!
echo.

REM Create directories
echo [3/10] Creating data directories...
if not exist "data" mkdir data
if not exist "data\raw" mkdir data\raw
if not exist "data\features" mkdir data\features
if not exist "data\models" mkdir data\models
if not exist "data\logs" mkdir data\logs
if not exist "data\logs\audit" mkdir data\logs\audit
echo Directories created!
echo.

REM Start configuration
echo [4/10] CONFIGURATION - Trading Parameters
echo ================================================================================
echo.

REM Portfolio size
:set_portfolio
set /p PORTFOLIO="Enter your portfolio size in USD (200-10000): "
if "%PORTFOLIO%"=="" goto set_portfolio
echo Portfolio size: $%PORTFOLIO%
echo.

REM Risk mode
:set_risk
echo Select Risk Mode:
echo   1 = Conservative (1%% per trade, 5%% daily - SAFEST)
echo   2 = Balanced (3%% per trade, 15%% daily - RECOMMENDED)
echo   3 = Aggressive (5%% per trade, 25%% daily - RISKY)
set /p RISK_CHOICE="Enter choice (1-3): "

if "%RISK_CHOICE%"=="1" (
    set RISK_MODE=conservative
    echo Risk mode: Conservative
) else if "%RISK_CHOICE%"=="2" (
    set RISK_MODE=balanced
    echo Risk mode: Balanced
) else if "%RISK_CHOICE%"=="3" (
    set RISK_MODE=aggressive
    echo Risk mode: Aggressive
) else (
    echo Invalid choice!
    goto set_risk
)
echo.

REM Universe size
:set_universe
set /p UNIVERSE="Number of trading pairs (5-20, recommended 10): "
if "%UNIVERSE%"=="" set UNIVERSE=10
echo Universe size: %UNIVERSE% pairs
echo.

REM Kill switch password
echo [5/10] SECURITY - Emergency Controls
echo ================================================================================
:set_password
set /p KILL_PASSWORD="Enter kill switch password (min 8 characters): "
if "%KILL_PASSWORD%"=="" goto set_password
echo Kill switch password set
echo.

REM API Keys
echo [6/10] API KEYS - Kraken Configuration
echo ================================================================================
echo.
echo You need 5 Kraken API key pairs from: https://www.kraken.com/u/security/api
echo.
echo Each key needs these permissions:
echo   - Query Funds
echo   - Query Open Orders and Trades
echo   - Query Closed Orders and Trades
echo   - Create and Modify Orders
echo   - Cancel/Close Orders
echo.
pause

REM Get 5 API keys
echo Enter your 5 Kraken API key pairs:
echo.

echo API KEY PAIR 1:
set /p KEY1="  Key 1: "
set /p SECRET1="  Secret 1: "
echo.

echo API KEY PAIR 2:
set /p KEY2="  Key 2: "
set /p SECRET2="  Secret 2: "
echo.

echo API KEY PAIR 3:
set /p KEY3="  Key 3: "
set /p SECRET3="  Secret 3: "
echo.

echo API KEY PAIR 4:
set /p KEY4="  Key 4: "
set /p SECRET4="  Secret 4: "
echo.

echo API KEY PAIR 5:
set /p KEY5="  Key 5: "
set /p SECRET5="  Secret 5: "
echo.

REM Advanced options
echo [7/10] ADVANCED OPTIONS (press Enter for defaults)
echo ================================================================================
echo.

set /p CONFIDENCE="Confidence threshold 0.50-0.90 (default 0.65): "
if "%CONFIDENCE%"=="" set CONFIDENCE=0.65

set /p EDGE_BUFFER="Edge buffer in basis points (default 20): "
if "%EDGE_BUFFER%"=="" set EDGE_BUFFER=20

set /p MAX_DRAWDOWN="Max daily drawdown %% (default 10): "
if "%MAX_DRAWDOWN%"=="" set MAX_DRAWDOWN=10

set /p MAX_LOSSES="Max consecutive losses (default 5): "
if "%MAX_LOSSES%"=="" set MAX_LOSSES=5

echo.

REM Create .env file
echo [8/10] Creating configuration file (.env)...

(
echo # ML Kraken Pro Live Trader - Configuration
echo # Generated by setup wizard on %date% %time%
echo.
echo # =============================================================================
echo # TRADING CONFIGURATION
echo # =============================================================================
echo LIVE_TRADING=1
echo PORTFOLIO_SIZE_USD=%PORTFOLIO%
echo RISK_MODE=%RISK_MODE%
echo.
echo # =============================================================================
echo # KRAKEN API KEYS
echo # =============================================================================
echo KRAKEN_KEY_1=%KEY1%
echo KRAKEN_SECRET_1=%SECRET1%
echo.
echo KRAKEN_KEY_2=%KEY2%
echo KRAKEN_SECRET_2=%SECRET2%
echo.
echo KRAKEN_KEY_3=%KEY3%
echo KRAKEN_SECRET_3=%SECRET3%
echo.
echo KRAKEN_KEY_4=%KEY4%
echo KRAKEN_SECRET_4=%SECRET4%
echo.
echo KRAKEN_KEY_5=%KEY5%
echo KRAKEN_SECRET_5=%SECRET5%
echo.
echo # =============================================================================
echo # UNIVERSE CONFIGURATION
echo # =============================================================================
echo BASE_QUOTE=USD
echo UNIVERSE_SIZE=%UNIVERSE%
echo UNIVERSE_REFRESH_MINUTES=60
echo MIN_DAILY_VOLUME_USD=1000000
echo.
echo # =============================================================================
echo # RISK MANAGEMENT
echo # =============================================================================
echo MAX_POSITION_PCT=3
echo MAX_DAILY_VOLUME_PCT=15
echo MAX_CONCURRENT_POSITIONS=5
echo MAX_DAILY_DRAWDOWN_PCT=%MAX_DRAWDOWN%
echo MAX_WEEKLY_DRAWDOWN_PCT=20
echo EDGE_BUFFER_BPS=%EDGE_BUFFER%
echo FEE_MULTIPLIER=3
echo MAX_SINGLE_ASSET_PCT=25
echo.
echo # =============================================================================
echo # PERFORMANCE TUNING
echo # =============================================================================
echo MAX_DECISION_LATENCY_MS=100
echo ORDER_TIMEOUT_SECONDS=30
echo FEATURE_LOOKBACK_SECONDS=300
echo WEBSOCKET_HEARTBEAT_TIMEOUT=30
echo FEATURE_CACHE_SIZE_MB=512
echo DATA_RETENTION_DAYS=90
echo.
echo # =============================================================================
echo # MODEL CONFIGURATION
echo # =============================================================================
echo MODEL_RETRAIN_HOURS=24
echo TRAINING_WINDOW_DAYS=30
echo VALIDATION_DAYS=1
echo MIN_TRAINING_SAMPLES=10000
echo CONFIDENCE_THRESHOLD=%CONFIDENCE%
echo CONFIDENCE_THRESHOLD_AGGRESSIVE=0.55
echo ENSEMBLE_MODELS=true
echo ENABLE_CROSS_ASSET_FEATURES=true
echo ENABLE_TEMPORAL_FEATURES=true
echo ENABLE_VOLATILITY_REGIMES=true
echo.
echo # =============================================================================
echo # SYSTEM CONFIGURATION
echo # =============================================================================
echo LOG_LEVEL=INFO
echo LOG_RETENTION_DAYS=30
echo ENABLE_TRADE_LOGGING=true
echo METRICS_PORT=8080
echo HEALTH_CHECK_PORT=8081
echo.
echo # =============================================================================
echo # EMERGENCY CONTROLS
echo # =============================================================================
echo KILL_SWITCH_PASSWORD=%KILL_PASSWORD%
echo CIRCUIT_BREAKER_COOLDOWN_MINUTES=60
echo MAX_CONSECUTIVE_LOSSES=%MAX_LOSSES%
echo ENABLE_CIRCUIT_BREAKERS=true
echo ENABLE_SPREAD_PROTECTION=true
echo SPREAD_PERCENTILE_THRESHOLD=95
echo ENABLE_LATENCY_PROTECTION=true
echo MAX_API_LATENCY_MS=500
echo.
echo # =============================================================================
echo # ADVANCED SETTINGS
echo # =============================================================================
echo MAKER_ORDER_PRICE_IMPROVEMENT_BPS=1
echo ICEBERG_THRESHOLD_USD=100
echo ORDER_SIZE_RANDOMIZATION_PCT=5
echo REQUESTS_PER_KEY_PER_SECOND=1
echo RATE_LIMIT_COOLDOWN_SECONDS=10
echo ORDERBOOK_DEPTH_LEVELS=10
echo TICK_DATA_BUFFER_SIZE=10000
echo MIN_SHARPE_RATIO=0.5
echo MIN_MODEL_ACCURACY=0.55
echo MODEL_DRIFT_THRESHOLD=0.1
echo ENABLE_ASSET_RESTRICTIONS=true
echo ENABLE_AUDIT_LOGGING=true
echo AUDIT_LOG_RETENTION_DAYS=365
) > .env

echo Configuration file created: .env
echo.

REM Validate configuration
echo [9/10] Validating configuration...
python -c "from bot.config import get_settings; s=get_settings(); print(f'Portfolio: ${s.portfolio_size_usd}'); print(f'Risk Mode: {s.risk_mode.value}'); print(f'API Keys: {len(s.api_keys)} configured'); print('Configuration is VALID!')" 2>nul
if errorlevel 1 (
    echo WARNING: Configuration validation failed
    echo Please review .env file manually
) else (
    echo Configuration validated successfully!
)
echo.

REM Summary
echo [10/10] SETUP COMPLETE!
echo ================================================================================
echo.
echo Configuration Summary:
echo ---------------------
echo Portfolio Size: $%PORTFOLIO%
echo Risk Mode: %RISK_MODE%
echo Trading Pairs: %UNIVERSE%
echo Confidence Threshold: %CONFIDENCE%
echo Kill Switch Password: [HIDDEN]
echo API Keys: 5 configured
echo.
echo Files Created:
echo   .env (configuration)
echo   data/ (data directories)
echo.
echo Next Steps:
echo   1. Review configuration: notepad .env
echo   2. Test API connectivity: configure.bat (option 2)
echo   3. Start trading: launch.bat
echo.
echo IMPORTANT REMINDERS:
echo   - This system uses REAL MONEY
echo   - Start with small capital ($200-500)
echo   - Monitor closely for first 24-48 hours
echo   - Emergency stop: Ctrl+C or create data\.kill_switch
echo.
echo ================================================================================
echo.
pause
