@echo off
REM Configuration script for Kraken Live Trading System
REM Allows user to configure API keys and system settings

echo ========================================
echo Kraken Live Trading System - Configuration
echo ========================================
echo.
echo This script will help you configure the trading system.
echo You will need your Kraken API keys ready.
echo.
pause

set CONFIG_FILE=.env

REM Check if .env exists, if not create template
if not exist %CONFIG_FILE% (
    echo Creating new configuration file...
    (
        echo # Kraken Live Trading System Configuration
        echo # Generated by configure.bat
        echo.
        echo # Trading Configuration
        echo LIVE_TRADING=1
        echo PORTFOLIO_SIZE_USD=500
        echo RISK_MODE=balanced
        echo.
        echo # API Configuration - Enter your Kraken API keys below
        echo KRAKEN_KEY_1=
        echo KRAKEN_SECRET_1=
        echo KRAKEN_KEY_2=
        echo KRAKEN_SECRET_2=
        echo KRAKEN_KEY_3=
        echo KRAKEN_SECRET_3=
        echo KRAKEN_KEY_4=
        echo KRAKEN_SECRET_4=
        echo KRAKEN_KEY_5=
        echo KRAKEN_SECRET_5=
        echo.
        echo # Risk Management
        echo MAX_POSITION_PCT=3
        echo MAX_DAILY_VOLUME_PCT=15
        echo MAX_DAILY_DRAWDOWN_PCT=10
        echo MAX_CONSECUTIVE_LOSSES=5
        echo.
        echo # Model Configuration
        echo CONFIDENCE_THRESHOLD=0.65
        echo ENSEMBLE_MODELS=true
        echo.
        echo # System Configuration
        echo LOG_LEVEL=INFO
        echo.
        echo # Emergency Controls
        echo KILL_SWITCH_PASSWORD=
    ) > %CONFIG_FILE%
    echo Configuration template created.
    echo.
)

echo.
echo ========================================
echo Configuration Editor
echo ========================================
echo.
echo The configuration file (.env) has been created or already exists.
echo.
echo IMPORTANT: You MUST edit .env manually to add your API keys.
echo.
echo Required configuration:
echo   - At least one KRAKEN_KEY_X and KRAKEN_SECRET_X (5 recommended)
echo   - PORTFOLIO_SIZE_USD (between $200-$800)
echo   - RISK_MODE (conservative, balanced, or aggressive)
echo   - KILL_SWITCH_PASSWORD (for emergency stops)
echo.
echo Opening configuration file...
timeout /t 2 >nul

REM Try to open with default editor
start notepad %CONFIG_FILE%

echo.
echo ========================================
echo Configuration Instructions
echo ========================================
echo.
echo 1. Add your Kraken API keys to the .env file
echo 2. Set your portfolio size (between $200-$800)
echo 3. Choose risk mode:
echo    - conservative: 1%% per trade, 5%% daily, 65%% confidence
echo    - balanced: 3%% per trade, 15%% daily, 60%% confidence
echo    - aggressive: 5%% per trade, 25%% daily, 55%% confidence
echo 4. Set a kill switch password
echo 5. Save and close the file
echo.
echo WARNING: Never share your API keys or commit them to version control!
echo.
pause

echo.
echo Configuration complete. You can now run start_bot.bat
pause
